# Generated by Django 3.0.3 on 2020-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.IntegerField()),
                ('priority', models.CharField(default='', max_length=200)),
                ('discription', models.TextField(blank=True, default='')),
                ('warn_from', models.DateTimeField(default='')),
                ('failure_after', models.DateTimeField(default='')),
                ('created', models.DateTimeField(default='')),
                ('modified', models.DateTimeField(default='')),
            ],
            options={
                'verbose_name_plural': 'SLA',
            },
        ),
    ]
