# Generated by Django 3.0.3 on 2020-03-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.IntegerField()),
                ('issue_details', models.TextField(blank='Flase', null='False')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MODERATE', 'Moderate')], max_length=200)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=200, null=True)),
                ('customer_details', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Customer')),
                ('employee_details', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
            ],
            options={
                'verbose_name_plural': 'SLA',
            },
        ),
    ]
