# Generated by Django 3.0.4 on 2020-03-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200330_1149'),
        ('SLA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='failure_after',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='sla',
            name='warn_from',
        ),
        migrations.AddField(
            model_name='sla',
            name='customer_details',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Account'),
        ),
        migrations.AddField(
            model_name='sla',
            name='employee_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount'),
        ),
        migrations.AddField(
            model_name='sla',
            name='issue_details',
            field=models.TextField(blank='Flase', null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='sla',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sla',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MODERATE', 'Moderate')], max_length=200),
        ),
    ]
