# Generated by Django 3.0.3 on 2020-04-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('SLA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='customer_details',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Customer'),
        ),
        migrations.AddField(
            model_name='sla',
            name='responsible_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile'),
        ),
    ]
