# Generated by Django 3.0.3 on 2020-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_client', models.CharField(max_length=20, null=True)),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('Invoice_number', models.CharField(max_length=30)),
                ('cust_sno', models.CharField(max_length=20, null=True, verbose_name='customerID')),
                ('Invoice_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('Tax', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('description', models.TextField(max_length=250, null=True)),
                ('payment_terms', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_client', models.CharField(max_length=50, null=True)),
                ('vendor_name', models.CharField(max_length=50, null=True)),
                ('InvoiceNumber', models.CharField(max_length=50)),
                ('vendor_sn', models.CharField(max_length=20, null=True, verbose_name='vendorID')),
                ('PO_Date', models.DateField()),
                ('rate_or_price', models.IntegerField()),
                ('Tax', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('description', models.TextField(max_length=250, null=True)),
                ('payment_terms', models.TextField(max_length=250, null=True)),
            ],
        ),
    ]
