# Generated by Django 3.0.4 on 2020-04-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_company', models.CharField(max_length=50, null=True)),
                ('vendor_name', models.CharField(max_length=50, null=True)),
                ('PO_Number', models.CharField(max_length=50)),
                ('vendor_sn', models.CharField(max_length=20, null=True, verbose_name='vendorID')),
                ('PO_Date', models.DateField()),
                ('Vendor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_company', models.CharField(max_length=20, null=True)),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('Invoice_number', models.CharField(max_length=30)),
                ('Invoice_date', models.DateField()),
                ('payment_terms', models.TextField(max_length=250, null=True)),
                ('customer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Customer')),
            ],
        ),
    ]
