# Generated by Django 3.0.4 on 2020-04-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': 'invoice'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name_plural': 'purchaseOrder'},
        ),
    ]
