# Generated by Django 3.0.3 on 2020-04-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200408_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_sn',
        ),
    ]
