# Generated by Django 3.0.4 on 2020-03-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200330_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='serviceTAG',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='ItemTAG',
            new_name='Items',
        ),
    ]
