# Generated by Django 3.0.3 on 2020-04-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Total',
        ),
    ]
