# Generated by Django 3.0.3 on 2020-03-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='Qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='SubTotal',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='Tax',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price',
        ),
    ]
