# Generated by Django 3.0.4 on 2020-04-26 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_purchaseorder_managed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='managed_By',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
