# Generated by Django 3.0.4 on 2020-04-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200426_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='managed_By',
            new_name='user',
        ),
    ]
