# Generated by Django 3.0.3 on 2020-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20200413_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
