# Generated by Django 3.0.3 on 2020-04-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20200413_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Total',
        ),
    ]
