# Generated by Django 3.0.3 on 2020-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20200414_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
