# Generated by Django 3.0.3 on 2020-04-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_purchaseorder_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Total',
            new_name='STotal',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Total',
            new_name='PTotal',
        ),
    ]
