# Generated by Django 3.0.3 on 2020-04-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20200414_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='STotal',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='PTotal',
            new_name='Total',
        ),
    ]
