# Generated by Django 3.0.4 on 2020-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptId', models.CharField(max_length=10)),
                ('dept_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('leave_days', models.PositiveIntegerField()),
                ('sick_days', models.PositiveIntegerField()),
                ('no_of_holidays_allowed', models.IntegerField()),
                ('package', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
