# Generated by Django 3.0.3 on 2020-03-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0001_initial'),
        ('payroll', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='departmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.Department'),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='packageId',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeePackage'),
        ),
    ]
