# Generated by Django 3.0.4 on 2020-04-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20200402_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'department'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name_plural': 'staffProfile'},
        ),
    ]
