# Generated by Django 3.0.3 on 2020-04-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20200407_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='joined_date',
            new_name='Joining_date',
        ),
    ]
