# Generated by Django 3.0.3 on 2020-03-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_staffprofile_packageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='departmentId',
            new_name='department',
        ),
    ]
