# Generated by Django 3.0.3 on 2020-03-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid')], max_length=20, null=True)),
                ('plan', models.CharField(max_length=20, null=True, verbose_name='plan')),
                ('validity', models.DateField(null=True)),
                ('dateOfBooking', models.DateField(null=True)),
                ('dateOfBill', models.DateField(null=True)),
                ('dueDate', models.DateField(null=True)),
                ('terms', models.TextField(max_length=250, null=True, verbose_name='PlanTerms')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=20)),
                ('Company_name', models.CharField(max_length=20)),
                ('Product_Description', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceId', models.CharField(max_length=50, null=True)),
                ('name_c', models.CharField(max_length=100, null=True, verbose_name='company')),
                ('Type', models.CharField(default='Unknown', max_length=20, null=True, verbose_name='Type')),
                ('description', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('isActive', models.BooleanField(default='true')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Invoice')),
            ],
        ),
    ]
