# Generated by Django 3.0.3 on 2020-04-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceentry',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='serviceentry',
            name='service',
        ),
        migrations.DeleteModel(
            name='ProductEntry',
        ),
        migrations.DeleteModel(
            name='ServiceEntry',
        ),
    ]
