# Generated by Django 3.0.4 on 2020-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Type',
            field=models.CharField(max_length=20, null=True, verbose_name='Type'),
        ),
    ]
