# Generated by Django 3.0.3 on 2020-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddServiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Qty', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Tax', models.IntegerField()),
                ('SubTotal', models.IntegerField()),
                ('service', models.ManyToManyField(to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='AddProductEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Qty', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Tax', models.IntegerField()),
                ('SubTotal', models.IntegerField()),
                ('Product', models.ManyToManyField(to='services.Product')),
            ],
        ),
    ]
