# Generated by Django 3.0.4 on 2020-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200402_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(),
        ),
    ]
