# Generated by Django 3.0.4 on 2020-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200330_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid')], max_length=20, null=True)),
                ('plan', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='Unknown', max_length=20, null=True, verbose_name='plan')),
                ('validity', models.DateField(null=True)),
                ('dateOfBooking', models.DateField(null=True)),
                ('dateOfBill', models.DateField(null=True)),
                ('dueDate', models.DateField(null=True)),
                ('terms', models.TextField(max_length=250, null=True, verbose_name='PlanTerms')),
            ],
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='name_c',
        ),
        migrations.AlterField(
            model_name='service',
            name='Type',
            field=models.CharField(default='Unknown', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
