# Generated by Django 3.0.4 on 2020-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200402_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
