# Generated by Django 3.0.3 on 2020-03-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200331_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproductentry',
            name='Product',
        ),
        migrations.AddField(
            model_name='addproductentry',
            name='Product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Product'),
        ),
        migrations.RemoveField(
            model_name='addserviceentry',
            name='service',
        ),
        migrations.AddField(
            model_name='addserviceentry',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
