# Generated by Django 3.0.3 on 2020-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200331_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproductentry',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addserviceentry',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
