# Generated by Django 3.0.4 on 2020-04-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200402_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='cost',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='serviceentry',
            old_name='cost',
            new_name='rate',
        ),
    ]
