# Generated by Django 3.0.3 on 2020-03-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200331_0138'),
        ('services', '0005_auto_20200331_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProductEntry',
            new_name='ProductEntry',
        ),
        migrations.RenameModel(
            old_name='AddServiceEntry',
            new_name='ServiceEntry',
        ),
    ]
