# Generated by Django 3.0.3 on 2020-03-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200331_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Product'),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
