# Generated by Django 3.0.4 on 2020-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200402_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='rate',
            field=models.FloatField(),
        ),
    ]
