# Generated by Django 3.0.4 on 2020-04-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200402_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'plan'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
    ]
