# Generated by Django 3.0.4 on 2020-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_id', models.CharField(max_length=150, null=True)),
                ('contact', models.IntegerField(max_length=10, null=True)),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.TextField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployeeAccount',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=150, null=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField(max_length=10, null=True)),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.TextField(max_length=150, null=True)),
                ('govt_id', models.CharField(max_length=150, null=True, unique=True)),
                ('employee_id', models.TextField(max_length=250, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=150, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('HR', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
