# Generated by Django 3.0.4 on 2020-03-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployeeaccount',
            name='email_id',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
