# Generated by Django 3.0.4 on 2020-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200312_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomeraccount',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useremployeeaccount',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
