# Generated by Django 3.0.4 on 2020-03-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200312_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployeeaccount',
            name='userName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
