# Generated by Django 3.0.4 on 2020-03-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200313_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremployeeaccount',
            old_name='userName',
            new_name='username',
        ),
    ]
