# Generated by Django 3.0.4 on 2020-03-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_id', models.CharField(max_length=150, null=True)),
                ('govt_id', models.CharField(choices=[('driving license', 'DRIVING LICENSE'), ('passport', 'PASSPORT'), ('aadhar', 'AADHAR CARD'), ('other', 'OTHER')], max_length=150, null=True, unique=True)),
                ('id_no', models.CharField(max_length=150, null=True, verbose_name='')),
                ('p_id1', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('SKYPE', 'Skype'), ('OTHER', 'Other')], max_length=150, null=True, verbose_name='PersonalID')),
                ('p_id_link', models.CharField(max_length=500, null=True, unique=True, verbose_name='')),
                ('contact', models.CharField(max_length=20, null=True, verbose_name='PhoneNo.')),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=150, null=True)),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
    ]
