# Generated by Django 3.0.3 on 2020-04-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
