# Generated by Django 3.0.3 on 2020-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customer_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='company_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
