# Generated by Django 3.0.4 on 2020-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200426_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER USER', 'super user'), ('MANAGER', 'manager'), ('HR', 'hr'), ('STAFF', 'staff')], max_length=20, null=True, verbose_name='user role'),
        ),
    ]
