# Generated by Django 3.0.4 on 2020-04-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200402_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'company'},
        ),
    ]
