# Generated by Django 3.0.4 on 2020-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('authentication', '0002_auto_20200330_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=150, null=True)),
                ('companyAddress1', models.CharField(max_length=150, null=True)),
                ('companyAddress2', models.CharField(max_length=150, null=True)),
                ('companyPhone', models.CharField(max_length=150, null=True)),
                ('companyEmailId', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email_id', models.CharField(max_length=150, null=True)),
                ('govt_id', models.CharField(choices=[('driving license', 'DRIVING LICENSE'), ('passport', 'PASSPORT'), ('aadhar', 'AADHAR CARD'), ('other', 'OTHER')], max_length=150, null=True, unique=True)),
                ('id_no', models.CharField(max_length=150, null=True, verbose_name='')),
                ('p_id1', models.CharField(max_length=150, null=True, verbose_name='PersonalID')),
                ('p_id_link', models.CharField(max_length=500, null=True, unique=True, verbose_name='')),
                ('contact', models.CharField(max_length=20, null=True, verbose_name='PhoneNo.')),
                ('address_1', models.CharField(max_length=150, null=True)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=150, null=True)),
                ('companyName', models.CharField(max_length=150, null=True)),
                ('companyAddress1', models.CharField(max_length=150, null=True)),
                ('companyAddress2', models.CharField(max_length=150, null=True)),
                ('companyPhone', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='p_id1',
            field=models.CharField(max_length=150, null=True, verbose_name='PersonalID'),
        ),
    ]
