# Generated by Django 3.0.4 on 2020-03-30 06:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('authentication', '0003_auto_20200330_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyAddress1',
            new_name='company_Address1',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyAddress2',
            new_name='company_Address2',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyEmailId',
            new_name='company_EmailId',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyName',
            new_name='company_Name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyPhone',
            new_name='company_Phone',
        ),
    ]
