# Generated by Django 3.0.3 on 2020-04-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employeeprofile_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createdBy',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile'),
        ),
    ]
