# Generated by Django 3.0.4 on 2020-03-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('authentication', '0004_auto_20200330_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='companyAddress1',
            new_name='company_Address1',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='companyAddress2',
            new_name='company_Address2',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='companyName',
            new_name='company_EmailId',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='companyPhone',
            new_name='company_Name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_Phone',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
