# Generated by Django 3.0.3 on 2020-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200414_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='upload_documents',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
