# Generated by Django 3.0.4 on 2020-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('SLA', '0002_auto_20200330_1149'),
        ('authentication', '0005_auto_20200330_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='p_id1',
            field=models.CharField(max_length=150, null=True, verbose_name='PersonalID'),
        ),
    ]
