# Generated by Django 3.0.4 on 2020-03-30 07:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('ProjectManagement', '0002_auto_20200330_1149'),
        ('SLA', '0002_auto_20200330_1149'),
        ('HR', '0002_auto_20200328_1419'),
        ('payroll', '0001_initial'),
        ('authentication', '0006_auto_20200330_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeAccount',
            new_name='EmployeeProfile',
        ),
    ]
