# Generated by Django 3.0.3 on 2020-04-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_employeeprofile_upload_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
