# Generated by Django 3.0.4 on 2020-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200415_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='upload_documents',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
