# Generated by Django 3.0.4 on 2020-03-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePackage',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('package_amount', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('isActive', models.BooleanField(default='true')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployeePaymentBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAttendance', models.IntegerField()),
                ('totalDays', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('billId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeePackage')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentReceipt',
            fields=[
                ('paymentId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('salaryMonth', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MAY', 'MAY'), ('JUN', 'JUN'), ('JULY', 'JULY'), ('AUG', 'AUG'), ('SEP', 'SEP'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=20, null=True)),
                ('dateOfPayment', models.DateField()),
                ('modeOfPayment', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=100)),
                ('ReceiptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.UserEmployeePaymentBill')),
            ],
        ),
    ]
