# Generated by Django 3.0.4 on 2020-04-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPackage',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='packageId')),
                ('package_amount', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('isActive', models.BooleanField(default='true')),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeDays', models.PositiveIntegerField()),
                ('workingDays', models.PositiveIntegerField()),
                ('total_Salary_Amount', models.PositiveIntegerField()),
                ('EmpId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
                ('salaryId', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.SalaryPackage')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('salary', models.IntegerField()),
                ('dateOfPayment', models.DateField(null=True)),
                ('modeOfPayment', models.CharField(max_length=10)),
                ('unpaid_leaves_allowed', models.PositiveIntegerField()),
                ('paid_leaves_allowed', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=100, null=True)),
                ('empId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
                ('packageId', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.SalaryPackage')),
            ],
        ),
    ]
