# Generated by Django 3.0.4 on 2020-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='salaryMonth',
            field=models.DateField(null=True),
        ),
    ]
