# Generated by Django 3.0.3 on 2020-04-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepackage',
            old_name='pacckageId',
            new_name='packageId',
        ),
    ]
