# Generated by Django 3.0.4 on 2020-04-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_monthlysalary_salarymonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeepackage',
            options={'verbose_name_plural': 'employeePackage'},
        ),
        migrations.AlterModelOptions(
            name='monthlysalary',
            options={'verbose_name_plural': 'monthlySalary'},
        ),
        migrations.AlterModelOptions(
            name='salarypackage',
            options={'verbose_name_plural': 'salaryPackage'},
        ),
    ]
