# Generated by Django 3.0.4 on 2020-04-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20200402_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeepackage',
            options={'verbose_name_plural': 'employeeSalary'},
        ),
        migrations.RemoveField(
            model_name='employeepackage',
            name='packageId',
        ),
        migrations.AddField(
            model_name='employeepackage',
            name='pacckageId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salaryId',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeePackage'),
        ),
        migrations.DeleteModel(
            name='SalaryPackage',
        ),
    ]
