# Generated by Django 3.0.3 on 2020-04-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='employee_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile'),
        ),
        migrations.AddField(
            model_name='business_opportunity',
            name='responsible_person',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile'),
        ),
    ]
