# Generated by Django 3.0.4 on 2020-03-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200330_1149'),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='project',
            name='done',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='name',
        ),
        migrations.AddField(
            model_name='business_opportunity',
            name='employee_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_assigned',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='todolist',
            name='employee_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='update',
            field=models.CharField(max_length=300, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='business_opportunity',
            name='Company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business_opportunity',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='business_opportunity',
            name='followup_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='business_opportunity',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_stage',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('EXECUTION', 'Execution'), ('COMPLETION', 'Completion')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeAccount'),
        ),
    ]
