# Generated by Django 2.2.1 on 2020-08-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectManagement', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile'),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='responsible_person',
            field=models.ManyToManyField(to='authentication.EmployeeProfile'),
        ),
    ]
