# Generated by Django 2.2.1 on 2020-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_auto_20200819_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessopportunity',
            name='upload_documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
