# Generated by Django 3.0.5 on 2020-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('ProjectManagement', '0002_auto_20200402_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(to='authentication.EmployeeProfile'),
        ),
    ]
